### PR TITLE
Update to latest version of conllu

### PR DESCRIPTION
**Pull request by EmilStenstrom**

### CODE REVIEW

**Comment by EmilStenstrom** [comment]
?

**Comment by nguyenbh** [comment]
Thank you for submitting the PR. I closed it because there is not enough information on the PR to address the necessity of updating to the latest conllu.

**Comment by EmilStenstrom** [comment]
> Thank you for submitting the PR. I closed it because there is not enough information on the PR to address the necessity of updating to the latest conllu.

Thanks for clarifying! There's no particular reason to update, simply because I am the author of the conllu package, and would like to see people only use the latest version of it if possible. It makes handling support requests easier.

So feel free to accept it or not!

**Comment by wangxinyu0922** [comment]
Hi, thank you for the pull request. We will update the latest version of conllu in the next version of our code if there is no problem in running ACE with the latest conllu.

**Pull request closed without merging**
